spring:
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
          clone-on-start: true
          username: ${SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME}
          password: ${SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD}
          default-label: ${CONFIG_GIT_BRANCH:main}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://eureka-server.default.svc.cluster.local:8761/eureka/}
