spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}  # Default profile is "dev"

server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info


#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        git:
#          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
#          username: ${SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME}
#          password: ${SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD} # This is your PAT
#          clone-on-start: true
#          default-label: main
#  application:
#    name: config-server
#server:
#  port: 8888
#
#eureka:
#  client:
#    service-url:
#      defaultZone: "http://eureka-server.default.svc.cluster.local:8761/eureka/"
#  instance:
#    prefer-ip-address: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info