#server:
#  port: 8888  # Default Config Server port
#
#spring:
#  profiles:
#    active: native
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/configurations

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
          username: ${SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME}
          password: ${SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD} # This is your PAT
          clone-on-start: true
          default-label: main
  application:
    name: config-server
server:
  port: 8888
