spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB1_URL}
    username: ${DB1_USERNAME}
    password: ${DB1_PASSWORD}
    hikari:
      pool-name: LoginServicePool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka-service:9092
  redis:
    host: redis-service
    port: 6379

#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    baseline-description: "init"
#    baseline-version: 0
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#server:
#  port: 8090
#
#application:
#  config:
#    login-url: http://localhost:8082/api/v1/auth/login