spring:
#  profiles:
#    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/IoTMining_Login_DB_Server_1
    username: postgres
    password: 8506
    hikari:
      pool-name: LoginServicePool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 2000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      server:
        request:
          autotime:
            enabled:false
      base-path: /actuator